import type { TripInputs } from './route-api'
export type AmountRange={min_fen:number|null;max_fen:number|null;currency:string}
export type BudgetLine={line_id:string;label:string;category:string;transport_scope:string|null;unit:string;quantity:number;unit_amount:AmountRange;status:string;basis:string;included_in_line_id:string|null;quote_id:string|null;conditions:string[];citation_ids:string[];queried_at:string|null;activity_ids:string[];optional:boolean;include_optional:boolean;paid_fen:number;locked:boolean;is_synthetic:boolean}
export type TripBudget={people:number|null;days:number|null;nights:number|null;rooms:number|null;target_fen:number|null;target_locked:boolean;assumptions:string[];lines:BudgetLine[]}
export type GuideContent={walking_requirement:string;title:string;reason:string;dining:{day:number;window:string;strategy:string}[];lodging:{strategy:string;area_ids:string[]};assumptions:string[];unknowns:string[];impacts:string[];origin:string}
export type GuideView={walking:{state:string;label:string};walking_suggestion:string|null;budget_context:{known_conditions:string[];pending_conditions:string[]};title:string;reason:string;summary:string;origin:string;available:boolean;activities:{activity_id:string;name:string;day:number;period:string;stay:string;rest:string;highlight:string;locked_start:string|null;conditions:string[]}[];dining:{day:number;window:string;text:string}[];lodging:{text:string;areas:string[];rooms:number|null;nights:number|null};budget:{known_total:AmountRange;per_person:AmountRange|null;lines:(BudgetLine&{basis_label:string;unit_label:string;total:AmountRange;note:string})[];missing_categories:string[];paid_fen:number;target_note:string|null};budget_difference:{min_fen:number;max_fen:number}|null;assumptions:string[];tradeoffs:string[];unknowns:string[]}
export type Activity = {locked?:boolean;period?:string;region_origin?:string; spatial_status?:string; spatial_basis?:{kind:string;reference_id:string;text:string}[]; source_locations?:string[]; activity_id: string; name: string; region: string; description?: string; reference_kinds?: string[]; discovery_ids?:string[]; evidence_ids: string[]; conditions: string[]; provenance: string; day: number; stay_min: number | null; stay_max: number | null; rest_minutes: number | null; locked_start: string | null; timing_origin: string}
export type Draft = {hard_notes?:string[];planning_mode:string;start_constraint:string;end_constraint:string;guide:GuideContent;trip_budget:TripBudget;spatial: {intent:string; origin:string}; direction: string | null; days: number | null; driving: string; transport: string; walking_allowed: boolean|null; walking_origin:string; adjustment: string; adjustment_minutes?: number | null; inputs: TripInputs; first_day: number; first_period: string; anchor_origin: string; return_deadline: string | null; activities: Activity[]}
export type Proposal = {changes?:RevisionChange[];title: string; reason: string; first_start: string | null; proposal_id?:string; fixed_origin?:string; transport: string; activities: {activity_id: string; day: number; stay_min: number; stay_max: number; rest_minutes: number}[]; citation_ids: string[]; assumptions: string[]; unknowns: string[]; impacts: string[]}
export type PlaceLead = {lead_id:string;public_name:string;start:number;end:number;parent_blocks:{block_index:number;text:string}[];quarantined:boolean;quarantine_reasons:string[];identity_status:string;identity_origin:string;spatial_status:string;context_flags:string[];claim_references:{context_status:string}[]}
export type RevisionChange = {activity_id:string;field:string;before:number|string|null;after:number|string|null}
export type OperationGrant = {used:Record<string,number>;remaining:Record<string,number>;limits:Record<string,number>;closed:boolean;expired:boolean;current:boolean;tasks:string[];recipients:string[]}
export type PlanView = {guide_view?:GuideView|null;combination_candidates:Activity[];proposal_preview_active?:boolean;operation?:{research_status:string;map_status:string;history:OperationGrant[];current:OperationGrant|null;cumulative_used:Record<string,number>;active:boolean;status:string;model_configuration:string;map_configuration:string};reuse_options?:{key:string;activities:Activity[]}[];model_status?:string;place_leads:PlaceLead[];discovery_available:boolean;session_id: string; revision: number; destination: string; request: string; travel_kind: string; demo: string | null; mode: string; draft: Draft; adopted: Draft | null; collapsed: Record<string, boolean>; directions: {id: string; label: string; advice: string; origin: string}[]; timeline: {activity_id: string; name: string; day: number; start: string; end: string; display_start:string; display_end:string; timing_origin: string; locked: boolean; stay_min: number | null; stay_max: number | null; rest_minutes: number | null}[]; gaps: string[]; differences: string[]; evidence_count: number; direction_change_pending: boolean; cache_message: string; job: {job_id: string; status: string; request_revision: number; can_preview?:boolean; base_revision?:number; rule_version?:string; returned?:boolean; parsed?:boolean; isolated_count?:number; local_diagnostic?:{replayable:boolean}; base_activities?:{activity_id:string;name:string;stay_min:number;stay_max:number;rest_minutes:number}[]; proposals: Proposal[]; protocol_version:number; accepted_count:number; rejected_count:number; generated_count:number | null; decisions:{proposal_id:string;status:string;reason:string;field:string | null;stage?:string;category?:string;rule_id?:string;rule_version?:string}[]; reason: string | null} | null; model_available: boolean; validation_trip: boolean; activity_candidates: Activity[]; references: {claim_id: string; text: string; conditions: string[]; reference_kind: string; source_title: string; review_status: string}[]; research_available: boolean; model_reason: string | null; private_budget: {used: Record<string,number>; remaining: Record<string,number>} | null; research_job: {status: string; can_adopt: boolean; new_evidence_count: number; reviewed: number; pending: number; rejected: number; reason: string | null} | null}
export type PlanIndex = {trips: {session_id: string; destination: string; demo: string | null}[]; current: PlanView | null; model_used: number; model_limit: number}
export const originLabel = (value: string) => ({AI_PROPOSED: '来自AI建议（事实未核实）', USER_CONFIRMED: '本行程用户输入', USER_INPUT: '本行程用户输入', SOURCE_REFERENCE: '来源参考，条件保留', SOURCE_MENTION:'原文仅提及地点（非已审核证据）', PRODUCT_DEFAULT: '可修改的产品建议', SYNTHETIC_TEST: '合成测试输入', UNKNOWN: '未定'}[value] || '未定')
export const transportLabel = (value: string) => ({UNKNOWN: '交通未定', PUBLIC_TRANSIT: '公共交通优先', SELF_DRIVE: '自己驾驶', LOCAL_SERVICE: '比较当地服务', WALKING: '步行优先'}[value] || '交通未定')
