<script setup lang="ts">
import {ref, watch} from 'vue'
import {request} from '../api'
import type {PlanView} from '../planning-api'
type Binding={card_id:string;version:number;card_hash:string}
type Card=Binding & {kind:string;title:string;entities:string[];text:string;conditions:string[];unknowns:string[];review_method:string;review_scope:string;test_input:boolean;spatial_status:string;attested_at:string;raw_availability:string;validation_basis:string;sources:{title:string;url:string|null;completeness:string;retrieved_at:string}[]}
type Result={cards:Card[];mode:string;source_count:number;bounded:boolean;gaps:string[]}
type Preview={cards?:Card[];skipped?:string[];preview_hash:string;items?:{characters:number}[];meaning?:string}
const props=defineProps<{plan:PlanView;busy:boolean;includeTest?:boolean}>()
const emit=defineEmits<{refresh:[sid:string];newtrip:[]}>()
const retention=ref('PERSISTENT')
const opened=ref(false),query=ref(''),region=ref(''),kind=ref(''),since=ref(''),includeTest=ref(false),waiting=ref(false),message=ref('')
const result=ref<Result|null>(null),selected=ref<string[]>([]),options=ref<{session_id:string;destination:string;validation_trip:boolean;adopted:boolean}[]>([]),sourceTrip=ref(''),preview=ref<Preview|null>(null),pending=ref(''),ack=ref(false)
const labels:Record<string,string>={SOURCE_REFERENCE:'来源知识',PLACE_LEAD:'地点线索',PLAN_PATTERN:'已采用节奏'}
const roles:Record<string,string>={WORK_REVIEWED:'历史开发审核',MODEL_CONTEXT_REVIEWED:'模型上下文审核',LOCAL_REVALIDATION:'本地重新校验',MENTION_LOCATED_ONLY:'仅核对名称提及',USER_ADOPTED_NOT_TRAVELED:'用户曾采用，未证明亲历'}
const refs=()=> (result.value?.cards||[]).filter(c=>selected.value.includes(c.card_id)).map(({card_id,version,card_hash})=>({card_id,version,card_hash}))
async function call<T>(action:string,extra:Record<string,unknown>={}){return (await request<{result:T}>('/api/v1/preview/knowledge',{action,...extra})).result}
async function search(){waiting.value=true;message.value='';try{result.value=await call<Result>('search',{query:query.value,destination:region.value,kind:kind.value,include_test:includeTest.value,since:since.value});selected.value=[]}catch(e){message.value=String(e)}finally{waiting.value=false}}
async function show(){opened.value=!opened.value;if(opened.value){await search();options.value=(await call<{options:typeof options.value}>('options')).options;sourceTrip.value=props.plan.session_id}}
async function prepare(action:string){waiting.value=true;message.value='';ack.value=false;try{pending.value=action;preview.value=await call<Preview>(action,{session_id:sourceTrip.value,refs:refs()})}catch(e){message.value=String(e)}finally{waiting.value=false}}
async function confirm(){waiting.value=true;try{const action=({preview_organize:'organize',preview_pattern:'save_pattern',preview_cleanup:'cleanup'} as Record<string,string>)[pending.value]!;await call(action,{session_id:sourceTrip.value,refs:refs(),preview_hash:preview.value?.preview_hash,confirm:true});preview.value=null;message.value=action==='cleanup'?'所选原文已逻辑清理；知识和账本保留。':'整理已保存在本机。';await search()}catch(e){message.value=String(e)}finally{waiting.value=false}}
async function attach(){waiting.value=true;try{await call('attach',{session_id:props.plan.session_id,expected_revision:props.plan.revision,refs:refs(),include_test:includeTest.value});opened.value=false;emit('refresh',props.plan.session_id);message.value='知识已加入这次草稿，尚未覆盖采用版。'}catch(e){message.value=String(e)}finally{waiting.value=false}}
async function saveRetention(){waiting.value=true;try{await call('retention',{refs:refs(),retention_policy:retention.value,confirm:true});message.value='已保存所选原文的保留偏好；不会自动清理，仍需单独预览和确认。'}catch(e){message.value=String(e)}finally{waiting.value=false}}
async function remove(action:string){waiting.value=true;try{await call(action,{refs:refs(),confirm:true});ack.value=false;pending.value='';await search();emit('refresh',props.plan.session_id)}catch(e){message.value=String(e)}finally{waiting.value=false}}
watch(()=>props.includeTest,v=>{if(v!==undefined){includeTest.value=v;void search()}},{immediate:true})
watch(()=>props.plan.session_id,()=>{region.value=props.plan.destination;preview.value=null;pending.value='';void search()},{immediate:true})
</script>
<template>
<section class="card library"><div class="heading"><h2>我的旅行资料</h2><button class="quiet" @click="show">{{opened?'收起资料库':'浏览与整理'}}</button></div>
<p>本机关键词检索 · 没有联网。当前目的地 {{result?.cards.length ?? 0}} 张匹配卡片；命中不代表条件充分。</p>
<template v-if="opened">
<div class="fields"><label>地区标签<input v-model="region" placeholder="精确地区，留空浏览所有" /></label><label>关键词<input v-model="query" placeholder="名称、交通或季节" @keyup.enter="search" /></label><label>类型<select v-model="kind"><option value="">全部类型</option><option v-for="(name,value) in labels" :key="value" :value="value">{{name}}</option></select></label><label>整理日期不早于<input v-model="since" type="date" /></label></div>
<label v-if="props.includeTest===undefined" class="check"><input v-model="includeTest" type="checkbox" />明确包含开发测试资料（不是长期偏好）</label><button :disabled="waiting||busy" @click="search">查询本机资料</button><p v-if="result">{{result.cards.length}} 张卡片，{{result.source_count}} 个不同来源标识；同源重复不算独立事实。{{result.bounded?'当前只展示有限范围，请缩小查询。':''}}</p>
<p v-if="result && !result.cards.length">没有符合筛选的本地知识；不会改名套用其他城市资料。可查看测试开关或整理已有资料。</p>
<article v-for="c in result?.cards" :key="c.card_id" class="entry"><label class="check"><input v-model="selected" type="checkbox" :value="c.card_id" />{{c.title}}</label><p>{{labels[c.kind]}} · {{roles[c.review_method]||c.review_method}} · {{c.test_input?'开发测试资料':'私人资料'}} · {{c.spatial_status==='MATCH'?'历史范围依据':'范围未核实/不适配'}}</p><p>{{c.text}}</p><ul><li v-for="v in c.conditions" :key="v">{{v}}</li></ul><details><summary>来源、角色与历史核对</summary><p>角色：{{c.review_scope}}；整理时核对：{{c.attested_at}}。{{c.raw_availability==='USER_CLEARED'?'原文已由用户清理，仅使用历史核对依据；不能重放原文审核。':'原文缓存仍在；本页检索不重新读取正文。'}}</p><p v-for="s in c.sources" :key="s.title">{{s.title}} · {{s.completeness}} · 取得于 {{s.retrieved_at}} <a v-if="s.url" :href="s.url" target="_blank" rel="noopener noreferrer">手动查看来源</a></p><p v-for="u in c.unknowns" :key="u">{{u}}</p></details></article>
<div class="actions"><button :disabled="waiting||busy||!selected.length||!!plan.adopted||!!plan.draft.activities.length" @click="attach">加入这次新旅行草稿</button><button class="quiet" @click="emit('newtrip')">先建立独立新旅行</button></div><p>新旅行只采用你选择的条目；旧日期、交通和测试偏好不会自动继承。已采用节奏只提供停留与顺序参考，不是实测。</p>
<details><summary>整理已有资料</summary><label>选择已有旅行<select v-model="sourceTrip"><option v-for="o in options" :key="o.session_id" :value="o.session_id">{{o.destination}} · {{o.validation_trip?'开发测试':'私人旅行'}} · {{o.adopted?'已采用':'草稿'}} · {{options.indexOf(o)+1}}</option></select></label><div class="actions"><button :disabled="waiting||!sourceTrip" @click="prepare('preview_organize')">预览整理已有资料</button><button :disabled="waiting||!sourceTrip" @click="prepare('preview_pattern')">预览保存已采用节奏</button></div></details>
<details><summary>分别管理原文和旅行知识</summary><p>清原文保留已整理知识、来源身份、审核记录、计划及额度。删除知识会禁止后续引用，旧采用版保留并提示依据不可用。两种操作都不退出登录。</p><label>所选原文保留偏好<select v-model="retention"><option value="PERSISTENT">长期保留（默认）</option><option value="READY_AFTER_ORGANIZED">整理成功后可清理</option><option value="SESSION">会话结束后可清理</option></select></label><p>后两项只记录清理偏好；本机不会自动删除，仍需下方影响预览和确认。</p><button class="quiet" :disabled="waiting||!selected.length" @click="saveRetention">保存所选保留偏好</button><div class="actions"><button class="quiet" :disabled="waiting||!selected.length" @click="prepare('preview_cleanup')">预览清理所选原文缓存</button><button class="quiet" :disabled="waiting||!selected.length" @click="pending='delete';ack=false;preview=null">删除所选旅行知识</button><button class="quiet" :disabled="waiting||!selected.length" @click="pending='withdraw';ack=false;preview=null">不再使用所选来源</button></div><template v-if="['delete','withdraw'].includes(pending)"><p>将移除所选条目的活跃检索和规划引用；来源撤销也会使依赖它的多来源卡失效。原文和已有计划保留。</p><label class="check"><input v-model="ack" type="checkbox" />确认以上影响</label><button :disabled="!ack||waiting" @click="remove(pending)">确认删除或撤销</button><button class="quiet" @click="pending=''">取消</button></template></details>
<section v-if="preview" class="entry"><h3>操作影响预览</h3><p v-if="preview.cards">本次 {{preview.cards.length}} 个可整理条目；同内容幂等，新条件保存新版本。跳过：{{preview.skipped?.join('、')||'无'}}。</p><ul><li v-for="(c,i) in preview.cards" :key="i">{{labels[c.kind]}}：{{c.title}}</li></ul><p v-if="preview.items">所选 {{preview.items.length}} 份原文；{{preview.meaning}}</p><label class="check"><input v-model="ack" type="checkbox" />确认本次预览范围</label><button :disabled="!ack||waiting" @click="confirm">确认这次操作</button><button class="quiet" @click="preview=null">取消</button></section>
<p role="status">{{message}}</p><p class="muted">向量检索未实现。本地关键词结果不会消除交通、季节或来源冲突。</p>
</template></section>
</template>
<style scoped>.library{margin:1rem 0}.heading{display:flex;align-items:center;justify-content:space-between}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.check{display:flex;gap:.5rem;align-items:center}.check input{width:auto}.entry{border:1px solid #cbd4ca;border-radius:12px;padding:1rem;margin:1rem 0}details{margin:.8rem 0}@media(max-width:650px){.fields{grid-template-columns:1fr}}</style>
